<?php if($quickviewGroup = $block->getGroupChildNames('quickview_tabs', 'getChildHtml')): ?>
<?php $sqLayout = $block->getLayout(); ?>
<?php $groupNum = count($quickviewGroup) ?>
<div class="qs-tab-wrap"
    <?php if($groupNum > 1): ?>
        data-mage-init='{"tabs":{"openedState":"active","content":".qs-tab-content","header":".qs-title",
"collapsibleElement":".qs-title"}}'
    <?php endif ?>
>
    <?php foreach ($quickviewGroup as $name):?>
    <?php
        $html = $sqLayout->renderElement($name);
        if (!trim($html)) {
            continue;
        }
        $alias = $sqLayout->getElementAlias($name);
        $contentId = $block->getChildData($alias,'html_id');
        $contentClass = $block->getChildData($alias,'html_class');
        $label = $block->getChildData($alias, 'title');
    ?>
    <?php if($groupNum > 1): ?>
    <div class="qs-title" aria-labeledby="tab-label-<?= $contentId;?>-title">
        <a class="data-switch" tabindex="-1" data-role="trigger" href="#<?= $contentId; ?>" id="tab-label-<?= $contentId;?>-title" data-toggle="switch">
            <?= $label; ?>
        </a>
    </div>
    <?php endif ?>
    <div class="qs-tab-content <?= $contentClass ?>" id="<?= $contentId; ?>">
        <?= $html; ?>
    </div>
    <?php endforeach ?>
</div>
<?php endif ?>