<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php if ($block->isEnabled()): ?>
    <div id="social-login-popup" class="white-popup mfp-with-anim mfp-hide"
         data-mage-init='{"socialPopupForm": <?php echo $block->getFormParams() ?>}'>
        <?= $block->getChildHtml('popup.email') ?>
        <?= $block->getChildHtml('popup.authentication') ?>
        <?php if ($block->getPopupCreate()) : ?>
            <?= $block->getChildHtml('popup.create') ?>
        <?php endif; ?>
        <?php if ($block->getPopupForgot()) : ?>
            <?= $block->getChildHtml('popup.forgot') ?>
        <?php endif; ?>
        <?= $block->getChildHtml('popup.additional.info') ?>
    </div>
    <div style="clear: both"></div>
<?php endif; ?>