<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if (count($block->getStores())>1): ?>
<div class="form-language">
    <label for="select-language"><?= /* @escapeNotVerified */ __('Your Language:') ?></label>
    <select id="select-language" title="<?= /* @escapeNotVerified */ __('Your Language') ?>" onchange="window.location.href=this.value" class="flags">
    <?php foreach ($block->getStores() as $_lang): ?>
        <?php $_selected = ($_lang->getId() == $block->getCurrentStoreId()) ? ' selected="selected"' : '' ?>
        <option value="<?= /* @escapeNotVerified */ $_lang->getCurrentUrl() ?>" style="background-image:url('<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/flags/flag_' . $_lang->getCode() . '.gif') ?>');"<?= /* @escapeNotVerified */ $_selected ?>><?= $block->escapeHtml($_lang->getName()) ?></option>
    <?php endforeach; ?>
    </select>
</div>
<?php endif; ?>
