<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Store switcher template
 *
 * @see \Magento\Store\Block\Store\Switcher
 */
?>
<?php if (count($block->getGroups())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="switcher store switcher-store" id="switcher-store<?= /* @escapeNotVerified */ $id?>">
    <strong class="label switcher-label"><span><?= /* @escapeNotVerified */ __('Select Store') ?></span></strong>
    <div class="actions dropdown options switcher-options">
        <?php foreach ($block->getGroups() as $_group): ?>
        <?php if ($_group->getId() == $block->getCurrentGroupId()): ?>
            <div class="action toggle switcher-trigger" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" id="switcher-store-trigger<?= /* @escapeNotVerified */ $id ?>">
                <strong>
                    <span><?= $block->escapeHtml($_group->getName()) ?></span>
                </strong>
            </div>
        <?php endif; ?>
        <?php endforeach; ?>
        
        <ul class="dropdown switcher-dropdown" data-mage-init='{"dropdownDialog":{
            "appendTo":"#switcher-store<?= /* @escapeNotVerified */ $id ?> > .options",
            "triggerTarget":"#switcher-store-trigger<?= /* @escapeNotVerified */ $id ?>",
            "closeOnMouseLeave": false,
            "triggerClass":"active",
            "parentClass":"active",
            "buttons":null}}'>
            <?php foreach ($block->getGroups() as $_group): ?>        	
            <?php if (!($_group->getId() == $block->getCurrentGroupId())): ?>
                <li class="switcher-option">
                    <a href="#" data-post='<?= /* @escapeNotVerified */ $block->getTargetStorePostData($_group->getDefaultStore()); ?>'>
                        <?= $block->escapeHtml($_group->getName()) ?>
                    </a>
                </li>
            <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
