<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php

$cfHelper   = $this->helper('MageBig\WidgetPlus\Helper\Config');
$id         = $block->getWidgetId();
$title      = $block->escapeHtml($block->getData('widget_title'), 'h2|h3|h4|h5|div|span|i|br|a');
$subtitle   = $block->escapeHtml($block->getData('widget_subtitle'), 'h2|h3|h4|h5|div|span|i|br|a');
$class      = $block->escapeHtmlAttr($block->getData('classes'));
$type       = $block->getData('product_type');
$carousel   = $block->getData('slider');
$collection = $block->getLoadedProductCollection();
$count      = 0;
if ($collection) {
    $count = $collection->count();
}
$showBlock = 1;
if ($count < 1 && ($type == 'related' || $type = 'crosssell' || $type = 'upsell')) {
    $showBlock = 0;
}
?>
<?php if ($showBlock) : ?>
    <div class="widgetplus widget-product <?= $type ?> <?= $class ?>" id="<?= $id ?>">
        <?php if ($title): ?>
            <div class="main-heading">
                <h2 class="heading-title"><span><?= __($title) ?></span></h2>
            </div>
        <?php endif ?>
        <?php if ($subtitle): ?>
            <div class="subtitle-widget"><span><?= __($subtitle) ?></span></div>
        <?php endif ?>

        <?php if ($count): ?>
            <?php
            $type          = 'widget-product-grid';
            $row           = $block->getData('row') ? (int)$block->getData('row') : 1;
            $pricePrefixId = $id;
            $column        = $carousel == 1 && $row == 1 ? $count : ($carousel == 1 && $row > 1 ? $row : $block->getData('column'));
            $image         = 'new_products_content_widget_grid';

            $showAddCart   = true;
            $showCompare   = true;
            $showWishlist  = true;
            $showRating    = true;
            $showQuickview = true;

            $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description     = false;
            $viewMode        = 'grid';
            $showDescription = false;

            $urlHelper   = $this->helper('Magento\Framework\Url\Helper\Data');
            $labelHelper = $this->helper('MageBig\WidgetPlus\Helper\Config');

            $productStyle = $block->getData('product_style');
            ?>
            <?php
            switch ($productStyle) {
                case '1' :
                    require $block->getTemplateFile('MageBig_WidgetPlus::widget/layout/product/product-style-01.phtml');
                    break;
                case '2' :
                    require $block->getTemplateFile('MageBig_WidgetPlus::widget/layout/product/product-style-02.phtml');
                    break;
                case '3' :
                    require $block->getTemplateFile('MageBig_WidgetPlus::widget/layout/product/product-style-03.phtml');
                    break;
                case '4' :
                    require $block->getTemplateFile('MageBig_WidgetPlus::widget/layout/product/product-style-04.phtml');
                    break;
                case '5' :
                    require $block->getTemplateFile('MageBig_WidgetPlus::widget/layout/product/product-style-05.phtml');
                    break;
                default :
                    require $block->getTemplateFile('MageBig_WidgetPlus::widget/layout/product/product-style-01.phtml');
                    break;
            }
            ?>
        <?php endif; ?>
    </div>

    <?php if ($carousel == 1): ?>
        <?php
        $autoplay        = is_numeric($block->getData('autoplay')) ? 'true' : 'false';
        $autoplayTimeout = is_numeric($block->getData('autoplay')) ? (int)$block->getData('autoplay') : 5000;
        $items           = $carousel == 1 ? (is_numeric($block->getData('column')) ? (int)$block->getData('column') : 4) : 1;
        $margin          = $carousel == 1 ? (is_numeric($block->getData('margin')) ? (int)$block->getData('margin') : 30) : 0;
        $nav             = (bool)$block->getData('navigation') ? 'true' : 'false';
        $dots            = (bool)$block->getData('paging') ? 'true' : 'false';
        $responsive      = $carousel == 1 ? $cfHelper->getCfRes($this->getData('x0'), $this->getData('x576'), $this->getData('x768'), $this->getData('x992'), $this->getData('x1200'), $this->getData('x1600')) : '{}';
        ?>
        <script type="text/x-magento-init">
            {
                "#<?= $id ?> .owl-carousel": {
                    "MageBig_WidgetPlus/js/owl.carousel-set": {
                        "autoplay"          : <?= $autoplay ?>,
                        "autoplayTimeout"   : <?= $autoplayTimeout ?>,
                        "items"             : <?= $items ?>,
                        "margin"            : <?= $margin ?>,
                        "nav"               : <?= $nav ?>,
                        "dots"              : <?= $dots ?>,
                        "responsive"        : <?= $responsive ?>
                    }
                }
            }
        </script>
    <?php endif; ?>

    <?php if ($block->getData('countdown')) : ?>
        <?php
            $dayText = 'd';
            $hourText = 'h';
            $minText = 'm';
            $secText = 's';
            $daySingularText = 'd';
            $hourSingularText = 'h';
            $minSingularText = 'm';
            $secSingularText = 's';
            if ($productStyle == 4) {
                $dayText = __('Days');
                $hourText = __('Hours');
                $minText = __('Mins');
                $secText = __('Secs');
                $daySingularText = __('Day');
                $hourSingularText = __('Hour');
                $minSingularText = __('Min');
                $secSingularText = __('Sec');
            }
        ?>
        <script type="text/x-magento-init">
            {
                "#<?= $id ?> > .category-products .sale-countdown": {
                    "MageBig_WidgetPlus/js/jcountdown-set": {
                        "dataAttr"          : "date",
                        "dayText"           : "<?= $dayText; ?>",
                        "hourText"          : "<?= $hourText; ?>",
                        "minText"           : "<?= $minText; ?>",
                        "secText"           : "<?= $secText; ?>",
                        "daySingularText"   : "<?= $daySingularText; ?>",
                        "hourSingularText"  : "<?= $hourSingularText; ?>",
                        "minSingularText"   : "<?= $minSingularText; ?>",
                        "secSingularText"   : "<?= $secSingularText; ?>",
                        "offset"            : <?= $cfHelper->getOffsetTimeZone(); ?>
                    }
                }
            }
        </script>
    <?php endif ?>

    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
                "[data-role=tocart-form], .form.map.checkout": {
                    "catalogAddToCart": {}
                }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>