<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
use Magento\Framework\App\Action\Action;
?>

<?php
$mbHelper = $this->helper('MageBig\MbFrame\Helper\Data');

$showAddCart = $mbHelper->getConfig('mbconfig/category_view/show_addcart');
$showCompare = $mbHelper->getConfig('mbconfig/category_view/show_compare');
$showWishlist = $mbHelper->getConfig('mbconfig/category_view/show_wishlist');
$showRating = $mbHelper->getConfig('mbconfig/category_view/show_rating');

switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $image_hover = 'related_products_list_hover';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $image_hover = 'related_products_list_hover';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $image_hover = 'upsell_products_list_hover';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $image_hover = 'upsell_products_list_hover';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $image_hover = 'cart_cross_sell_products_hover';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $image_hover = 'cart_cross_sell_products_hover';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $image_hover = 'new_products_content_widget_grid_hover';
            $title = __('New Products');
            $items = $exist;

            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>

<?php if ($exist):?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?= /* @escapeNotVerified */ $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= /* @escapeNotVerified */ $limit; ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle; ?>">
        <?php else: ?>
            <div class="block <?= /* @escapeNotVerified */ $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?= /* @escapeNotVerified */ $limit; ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle; ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?= /* @escapeNotVerified */ $class; ?>">
    <?php endif; ?>
    <div class="block-title title">
        <strong id="block-<?= /* @escapeNotVerified */ $class?>-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */ $title; ?></strong>
    </div>
    <div class="related-upsell-crossell block-content content" aria-labelledby="block-<?= /* @escapeNotVerified */ $class?>-heading">
        <?php if ($type == 'related' && $canItemsAddToCart): ?>
        <div class="block-actions">
            <?= /* @escapeNotVerified */ __('Check items to add to the cart or') ?>
            <button type="button" class="action select" role="select-all"><span><?= /* @escapeNotVerified */ __('select all') ?></span></button>
        </div>
        <?php endif; ?>
        <div class="products wrapper grid products-grid products-<?= /* @escapeNotVerified */ $type; ?>">
            <ol class="products list items product-items">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                <?php $available = ''; ?>
                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($type == 'related' || $type == 'upsell'): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item" style="display: none;">' : '</li><li class="item product product-item" style="display: none;">' ?>
                <?php else: ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <?php endif; ?>
                <div class="product-item-info <?= /* @escapeNotVerified */ $available; ?>">
                    <div class="product-show">
                        <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                            <span class="front"><?= $block->getImage($_item, $image)->toHtml(); ?></span>
                        </a>
                        <div class="product-btn">
                            <?= $this->helper('MageBig\QuickView\Helper\Data')->getQuickViewButton($_item,'mb-tooltip'); ?>
                        </div>
                    </div>
                    <?php if ($_item->getTypeId() == 'configurable') : ?>
                        <div class="swatches-list">
                            <?= $block->getProductDetailsHtml($_item); ?>
                        </div>
                    <?php endif; ?>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>"
                               title="<?= $block->escapeHtml($_item->getName()) ?>">
                                <?= $block->escapeHtml($_item->getName()) ?>
                            </a>
                        </strong>

                        <?php if ($showRating) : ?>
                            <?= $block->getReviewsSummaryHtml($_item, $templateType); ?>
                        <?php endif; ?>

                        <?= /* @escapeNotVerified */ $block->getProductPrice($_item); ?>

                        <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                            <?php if (!$_item->getRequiredOptions()): ?>
                                <div class="field choice related">
                                    <input type="checkbox" class="checkbox related" id="related-checkbox<?= /* @escapeNotVerified */ $_item->getId() ?>" name="related_products[]" value="<?= /* @escapeNotVerified */ $_item->getId() ?>" />
                                    <label class="label" for="related-checkbox<?= /* @escapeNotVerified */ $_item->getId() ?>"><span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span></label>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">
                                    <?php if ($_item->isSaleable()): ?>
                                        <?php
                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()]);
                                            $postParams = json_decode($postData,true);
                                        ?>
                                        <form data-role="tocart-form" action="<?= /* @escapeNotVerified */ $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED; ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?= $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary mb-tooltip">
                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_item->getIsSalable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <?php if ($showWishlist || $showCompare): ?>
                                    <div class="actions-secondary" data-role="add-to-links">
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                            <div class="btn-wishlist">
                                                <button type="button"
                                                   data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($_item); ?>'
                                                   class="action towishlist mb-tooltip" data-action="add-to-wishlist"
                                                   title="<?= /* @escapeNotVerified */ __('Add to Wishlist') ?>">
                                                    <span><i aria-hidden="true" class="icon_heart_alt"></i></span>
                                                </button>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                            <div class="btn-compare">
                                                <button type="button" class="action tocompare mb-tooltip"
                                                   data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataParams($_item);?>'
                                                   title="<?= /* @escapeNotVerified */ __('Add to Compare') ?>">
                                                    <span><i aria-hidden="true" class="icon_piechart"></i></span>
                                                </button>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?=($iterator == count($items)+1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
 <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
<?php endif; ?>
<?php endif;?>
