<?php
/**
 * MageSpecialist
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@magespecialist.it so we can send you a copy immediately.
 *
 * @category   MSP
 * @package    MSP_ReCaptcha
 * @copyright  Copyright (c) 2017 Skeeller srl (http://www.magespecialist.it)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/** @var $block MSP\ReCaptcha\Block\Frontend\ReCaptcha */
?>
<?php
$mbHelper = $this->helper('MageBig\MbFrame\Helper\Data');
$enabled = $mbHelper->getConfig('msp_securitysuite_recaptcha/frontend/enabled');

if ($enabled) : ?>
<?php
$obj = Zend_Json::decode($block->getJsLayout());

if (isset($obj['components']['msp-recaptcha'])) {
    $id = str_replace('.', '-', $this->getNameInLayout());
    $layout = $obj['components']['msp-recaptcha'];
    $obj['components'][$id] = $layout;
    $obj['components'][$id]['reCaptchaId'] = $id;
    unset($obj['components']['msp-recaptcha']);
    $obj = Zend_Json::encode($obj);
} else {
    $id = $block->getRecaptchaId();
    $obj = $block->getJsLayout();
}
?>
<div class="field-recaptcha" id="container-<?= $id ?>" data-bind="scope:'<?= $id ?>'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
{
    "#container-<?= $id ?>": {
        "Magento_Ui/js/core/app": <?= $obj ?>
    }
}
</script>
<?php endif; ?>