<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="main-newsletter">
    <div class="main-newsletter-inner">
        <div class="subscribe">
            <form
                novalidate
                action="<?= /* @escapeNotVerified */ $block->getFormActionUrl() ?>"
                method="post"
                data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                id="newsletter-validate-detail">
                <div class="block-content">
                    <div class="input-box">
                        <input name="email" type="email" id="newsletter"
                                    placeholder="<?= __('Enter your email here...') ?>"
                                    data-validate="{required:true, 'validate-email':true}"/>
                        <button class="hover-effect07" title="<?= /* @escapeNotVerified */ __('Subscribe') ?>" type="submit">
                            <span><?= /* @escapeNotVerified */ __('Subscribe') ?></span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
