<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */

$_mbHelper = $this->helper('MageBig\MbFrame\Helper\Data');
$id = $block->getGalleryId().$block->getProduct()->getId();
$images = $block->getGalleryImages()->getItems();
$imgCount = count($images);
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

?>
<div class="gallery-placeholder _block-content-loading gallery-<?= $id; ?> <?php if ($imgCount) echo 'imgs'; ?>">
    <img
            alt="main product photo"
            class="gallery-placeholder__image img-fluid"
            src="<?= /* @noEscape */ $mainImageData ?>"
    />
    <span class="thumb-pl"></span>
    <div data-role="loader" class="loading-mask">
        <div class="loader"></div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".gallery-<?= $id; ?>": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @escapeNotVerified */ $block->getMagnifier() ?>,
                "data": <?= /* @escapeNotVerified */ $block->getGalleryImagesJson() ?>,
                "options": {
                    "thumbmargin": 10,
                    "thumbborderwidth": 1,
                    "nav": "thumbs",
                    "loop": 1,
                    "keyboard": 1,
                    "arrows": 1,
                    <?php if ($_mbHelper->getConfig('mbconfig/product_view/allowfullscreen')): ?>
                        "allowfullscreen": <?= /* @escapeNotVerified */ $_mbHelper->getConfig('mbconfig/product_view/allowfullscreen') ?>,
                    <?php endif; ?>
                    "showCaption": 0,
                    "width": "<?= /* @escapeNotVerified */ $_mbHelper->getConfig('mbconfig/product_view/base_image_width') ?>",
                    "thumbwidth": "<?= /* @escapeNotVerified */ $_mbHelper->getConfig('mbconfig/product_view/thumbnail_width') ?>",
                    <?php if ($_mbHelper->getConfig('mbconfig/product_view/thumbnail_height') || $_mbHelper->getConfig('mbconfig/product_view/thumbnail_width')): ?>
                    "thumbheight": <?= /* @escapeNotVerified */ $_mbHelper->getConfig('mbconfig/product_view/thumbnail_height') ?: $_mbHelper->getConfig('mbconfig/product_view/thumbnail_width'); ?>,
                    <?php endif; ?>
                    <?php if ($_mbHelper->getConfig('mbconfig/product_view/base_image_height') || $_mbHelper->getConfig('mbconfig/product_view/base_image_width')): ?>
                        "height": <?= /* @escapeNotVerified */ $_mbHelper->getConfig('mbconfig/product_view/base_image_height') ?: $_mbHelper->getConfig('mbconfig/product_view/base_image_width'); ?>,
                    <?php endif; ?>
                    "transitionduration": 500,
                    "transition": "slide",
                    "navarrows": 1,
                    "navtype": "slides",
                    "navdir": "<?= /* @escapeNotVerified */ $_mbHelper->getConfig('mbconfig/product_view/nav_dir') ?>"
                },
                "fullscreen": {
                    "nav": "thumbs",
                    "loop": 1,
                    "navdir": "vertical",
                    "navtype": "slides",
                    "arrows": 1,
                    "showCaption": 1,
                    "transitionduration": 500,
                    "transition": "dissolve"
                },
                "breakpoints": {
                    "mobile":{
                        "conditions":{"max-width":"767px"},
                        "options": {
                            "options": {
                                "nav":"thumbs",
                                "navdir":"horizontal"
                            }
                        }
                    }
                }
            }
        }
    }
</script>

