<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()): ?>
    <div class="additional-attributes-wrapper table-wrapper">
        <table class="data table additional-attributes" id="product-attribute-specs-table">
            <tbody>
            <?php foreach ($_additional as $_data): ?>
                <?php //if ($_helper->productAttribute($_product, $_data['value'], $_data['code']) != __('N/A')) : ?>
                <tr>
                    <th class="label" scope="row"><?= $block->escapeHtml(__($_data['label'])) ?></th>
                    <td class="data" data-th="<?= $block->escapeHtml(__($_data['label'])) ?>"><?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
                </tr>
                <?php //endif; ?>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif;?>
