<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php $_product = $block->getProduct() ?>
<?php if ($_product->isSaleable() && $block->hasOptions()):?>
    <div class="bundle-actions">
        <button id="bundle-slide"
                class="action primary customize"
                type="button">
            <span><?= /* @escapeNotVerified */ __('Customize and Add to Cart') ?></span>
        </button>
    </div>
<?php endif;?>
