<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Review\Block\Form
 */
?>
<?php if ($block->getAllowWriteReviewFlag()): ?>
<form action="<?= /* @escapeNotVerified */ $block->getAction() ?>" class="review-form" method="post" id="review-form" data-role="product-review-form" data-bind="scope: 'review-form'">
    <?= $block->getBlockHtml('formkey'); ?>
    <?= $block->getChildHtml('form_fields_before')?>
    <fieldset class="fieldset review-fieldset" data-hasrequired="<?php __('* Required Fields'); ?>">
        <div class="row">
            <?php if ($block->getRatings() && $block->getRatings()->getSize()): ?>
                <div class="col-12 col-sm-12 col-md-5 col-lg-4">
                    <span id="input-message-box"></span>
                    <fieldset class="field required review-field-ratings">
                        <legend class="label"><span><?= /* @escapeNotVerified */ __('Your Rating') ?></span></legend><br/>
                        <div class="control">
                            <div class="nested" id="product-review-table">
                                <?php foreach ($block->getRatings() as $_rating): ?>
                                    <div class="field choice review-field-rating">
                                        <label class="label" id="<?= $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label"><span><?= $block->escapeHtml($_rating->getRatingCode()) ?></span></label>
                                        <div class="control review-control-vote">
                                        <?php $options = $_rating->getOptions();?>
                                        <?php $iterator = 1; foreach ($options as $_option): ?>
                                            <input
                                                type="radio"
                                                name="ratings[<?= /* @escapeNotVerified */ $_rating->getId() ?>]"
                                                id="<?= $block->escapeHtml($_rating->getRatingCode()) ?>_<?= /* @escapeNotVerified */ $_option->getValue() ?>"
                                                value="<?= /* @escapeNotVerified */ $_option->getId() ?>"
                                                class="radio"
                                                data-validate="{required:true, messages:{required:'Please select one of each of the ratings above.'}}"
                                                aria-labelledby="<?= $block->escapeHtml($_rating->getRatingCode()) ?>_rating_label <?= $block->escapeHtml($_rating->getRatingCode()) ?>_<?= /* @escapeNotVerified */ $_option->getValue() ?>_label" />
                                            <label
                                                class="rating-<?= /* @escapeNotVerified */ $iterator; ?>"
                                                for="<?= $block->escapeHtml($_rating->getRatingCode()) ?>_<?= /* @escapeNotVerified */ $_option->getValue() ?>"
                                                title="<?= /* @escapeNotVerified */ __('%1 %2', $iterator, $iterator > 1 ? 'stars' : 'star') ?>"
                                                id="<?= $block->escapeHtml($_rating->getRatingCode()) ?>_<?= /* @escapeNotVerified */ $_option->getValue() ?>_label">
                                                <span><?= /* @escapeNotVerified */ __('%1 %2', $iterator, $iterator > 1 ? 'stars' : 'star') ?></span>
                                            </label>
                                        <?php $iterator++; ?>
                                        <?php endforeach; ?>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                            <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                        </div>
                    </fieldset>
                </div>
            <?php endif ?>
            <div class="col-12 col-sm-12 col-md-7 col-lg-8">
                <div class="row">
                    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                        <div class="field review-field-nickname required">
                            <label for="nickname_field" class="label"><span><?= /* @escapeNotVerified */ __('Nickname') ?></span></label>
                            <div class="control">
                                <input type="text" name="nickname" id="nickname_field" class="input-text" data-validate="{required:true}" data-bind="value: nickname()" />
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
                        <div class="field review-field-summary required">
                            <label for="summary_field" class="label"><span><?= /* @escapeNotVerified */ __('Summary') ?></span></label>
                            <div class="control">
                                <input type="text" name="title" id="summary_field" class="input-text" data-validate="{required:true}" data-bind="value: review().title" />
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="field review-field-text required">
                            <label for="review_field" class="label"><span><?= /* @escapeNotVerified */ __('Review') ?></span></label>
                            <div class="control">
                                <textarea name="detail" id="review_field" cols="5" rows="3" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
                            </div>
                        </div>
                        <div class="actions-toolbar review-form-actions">
                            <div class="primary actions-primary">
                                <button type="submit" class="action submit primary"><span><?= /* @escapeNotVerified */ __('Submit Review') ?></span></button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
</form>
<script type="text/x-magento-init">
{
    "[data-role=product-review-form]": {
        "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout();?>
    },
    "#review-form": {
        "Magento_Review/js/error-placement": {}
    }
}
</script>
<?php else: ?>
    <div class="message info notlogged" id="review-form">
        <div>
            <?= /* @escapeNotVerified */ __('Only registered users can write reviews. Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()) ?>
        </div>
    </div>
<?php endif ?>
