<div class="magebig-ajax-popup ajaxwishlist-error-box zoom-anim-dialog">
    <p class="mb-message-error"><?= __('Please log in before adding product to your Wish List.'); ?></p>
    <div class="ajaxwishlist-buttons">
        <a href="<?= $block->getUrl('customer/account/login') ?>" id="ajaxwishlist-btn-login" class="action primary">
            <span><?= __('Log in') ?></span>
        </a>
    </div>
</div>