<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<div class="social-login block-container forgot" style="display:none">
    <form class="form password forget form-password-forget"
          id="social-form-password-forget"
          data-mage-init='{"validation":{}}'>
        <div class="social-login-title">
            <h2 class="forgot-pass-title"><?= __('Forgot Password') ?></h2>
        </div>
        <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
            <div class="field note"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
            <div class="field email required">
                <label for="email_address_forgot" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input type="email" name="email" id="email_address_forgot" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
                </div>
            </div>
            <?= $block->getChildHtml('form_additional_info') ?>
            <?php //echo $block->getChildHtml('forgot.captcha'); ?>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="button" class="action send primary"><span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
            </div>
            <div class="secondary">
                <a class="action back" href="#"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
            </div>
        </div>
    </form>
</div>