<?php
/**
 * Copyright © magebig.com - All rights reserved.
 * See LICENSE.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_menu = $block->getHtml(0, 'level-top', 'submenu'); ?>
<div class="horizontal-menu navigation">
    <ul class="smartmenu magebig-nav">
        <?= /* @escapeNotVerified */ $_menu; ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml(); ?>
    </ul>
</div>