<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/**  @var $block \Magento\Checkout\Block\Cart */
?>
<div class="cart-empty text-center">
    <?= $block->getChildHtml('checkout_cart_empty_widget') ?>
    <h2><?= /* @escapeNotVerified */ __('You have no items in your shopping cart.') ?></h2>
    <p>
        <a class="action primary" href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"><?= __('Continue shopping')?></a>
    </p>
    <?= $block->getChildHtml('shopping.cart.table.after') ?>
</div>

<script>
    require([
        'Magento_Customer/js/customer-data'
    ], function (customerData) {
        var sections = ['cart'];
        customerData.invalidate(sections);
    });
</script>